sudo: required
services:
  - docker

before_install:
  - docker build -t jonmully/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true jonmully/docker-react2 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-468883350109"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY